Add some explicit any and fixe missing import
Fixes these compilation errors for"noImplicitAny": true
typings/globals/graphql-relay/index.d.ts(171,25): error TS7006: Parameter 'Object' implicitly has an 'any' type.                                                                                                                                                            
typings/globals/graphql-relay/index.d.ts(171,33): error TS7006: Parameter 'GraphQLResolveInfo' implicitly has an 'any' type.                                                                                                                                                
typings/globals/graphql-relay/index.d.ts(172,11): error TS7006: Parameter 'Object' implicitly has an 'any' type.                                                                                                                                                            
typings/globals/graphql-relay/index.d.ts(172,19): error TS7006: Parameter 'GraphQLResolveInfo' implicitly has an 'any' type.                                                                                                                                                
typings/globals/graphql-relay/index.d.ts(192,29): error TS7006: Parameter 'any' implicitly has an 'any' type.                                                                                                                                                               
typings/globals/graphql-relay/index.d.ts(193,11): error TS7006: Parameter 'any' implicitly has an 'any' type.